src/clog/urls.py
from django.urls import path

from . import views

app_name = 'clog'

urlpatterns = [
    path('', views.index, name='index'),

    path('var/<int:pk>/',
         views.VariableDetail.as_view(),
         name='variable_detail'),

    path('var/<int:pk>/update/',
         views.VariableUpdate.as_view(),
         name='variable_update'),

    path('var/create/',
         views.VariableCreate.as_view(),
         name='variable_create'),

    path('charts/', views.update_charts, name='refresh_charts'),

    path('import_vars/', views.import_vars, name='import_vars'),

    path('import_entries/', views.import_entries, name='import_entries'),

    path('logentry/create/',
         views.logentry_create,
         name='logentry_create'),
    path('logentry/<int:pk>/',
         views.logentry_detail,
         name='logentry_detail'),
    path('logentry/<int:pk>/update/',
         views.logentry_update,
         name='logentry_update'),

    path('sharewith_list', views.ShareList.as_view(), name='share_index'),

    path('share/<int:pk>/',
         views.shareview,
         name='share_view'),

    path('share/<int:pk>/send_daily/',
         views.send_daily,
         name='send_daily'),

    path('share/<int:pk>/send_weekly/',
         views.send_weekly,
         name='send_weekly'),

    path('sharewith/<int:pk>/',
         views.ShareDetail.as_view(),
         name='share_detail'),

    path('sharewith/create/',
         views.ShareCreate.as_view(),
         name='share_create'),

    path('sharewith/<int:pk>/update/',
         views.ShareUpdate.as_view(),
         name='share_update'),

    path('<int:pk>/snooze',
         views.snooze,
         name='snooze'),

]

src/nexttask/urls.py
from django.urls import path
from nexttask import views

app_name = 'nexttask'

urlpatterns = [
    path('',
         views.TaskList.as_view(),
         name='task_list'),

    path('donesince/',
         views.TaskDoneSince.as_view(),
         name='task_done_since'),

    path('addedtoday/',
         views.TaskAddedToday.as_view(),
         name='task_added_today'),

    path('up_all_est/',
         views.update_all_estimates,
         name='update_all_estimates'),

    path('create/',
         views.TaskCreate.as_view(),
         name='task_create'),

    path('<int:pk>/',
         views.TaskRead.as_view(),
         name='task_read'),

    path('<int:pk>/move/',
         views.move_task,
         name='move_task'),

    path('<int:pk>/move_to_edge/',
         views.move_task_to_edge,
         name='move_task_to_edge'),

    path('<int:pk>/toggl_start/',
         views.start_toggl,
         name='start_toggl'),

    path('<int:pk>/snooze/',
         views.snooze,
         name='snooze'),

    path('<int:pk>/update/',
         views.TaskUpdate.as_view(),
         name='task_update'),

    path('<int:pk>/delete/',
         views.TaskDelete.as_view(),
         name='task_delete'),

    path('<int:pk>/explode/',
         views.explode,
         name='explode'),

    path('<int:pk>/slice/<int:key>',
         views.slice,
         name='slice'),

    path('<int:pk>/resolve_row/<int:key>',
         views.resolve_row,
         name='resolve_row'),

    path('<int:pk>/cut_row/<int:key>',
         views.cut_row,
         name='cut_row'),

    path('<int:pk>/done/',
         views.mark_task_done,
         name='mark_task_done'),

    path('tag/',
         views.TagList.as_view(),
         name='tag_list'),

    path('tag/create/',
         views.TagCreate.as_view(),
         name='tag_create'),

    path('tag/<int:pk>/',
         views.TagRead.as_view(),
         name='tag_read'),

    path('tag/<int:pk>/update/',
         views.TagUpdate.as_view(),
         name='tag_update'),

    path('tag/<int:pk>/delete/',
         views.TagDelete.as_view(),
         name='tag_delete'),

    path('mode/',
         views.FilterComboList.as_view(),
         name='filtercombo_list'),

    path('mode/<int:pk>/',
         views.FilterComboRead.as_view(),
         name='filtercombo_read'),

    path('nextline/',
         views.NextLineList.as_view(),
         name='nextline_list'),

    path('nextline/create/',
         views.NextLineCreate.as_view(),
         name='nextline_create'),

    path('nextline/<int:pk>/',
         views.NextLineRead.as_view(),
         name='nextline_read'),

    path('nextline/<int:pk>/update/',
         views.NextLineUpdate.as_view(),
         name='nextline_update'),

    path('nextline/<int:pk>/delete/',
         views.NextLineDelete.as_view(),
         name='nextline_delete'),

    path('nextline/<int:pk>/move_to_top/',
         views.move_nextline_to_top,
         name='nextline_move_to_top'),

    path('estimates/',
         views.EstimateList.as_view(),
         name='estimate'),

    path('phab_sync/',
         views.phabricator_sync,
         name='phabricator_sync'),

    path('airtable/',
         views.airtable_test,
         name='airtable_test'),

    path('map_toggl_tags/',
         views.map_toggl_tags,
         name='map_toggl_tags'),

    path('map_toggl_tasks/',
         views.map_toggl_tasks,
         name='map_toggl_tasks'),

    path('get_toggl_durations/',
         views.get_toggl_durations,
         name='get_toggl_durations'),
]

src/whatnext/urls.py
"""whatnext URL Configuration
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.urls import include, path
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'), # NOQA  https://stackoverflow.com/questions/35804554/importing-django-contrib-auth-urls-does-not-play-well-with-existing-admin-templa
    path('accounts/', include('django.contrib.auth.urls')),
    path('clog/', include('clog.urls')),
    path('nexttask/', include('nexttask.urls')),
]

if settings.DEBUG:
    from django.views import defaults
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += [
        path(r'media/<path>', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        path('500/', defaults.server_error, name='500'),
        path('styleguide', TemplateView.as_view(template_name='styleguide.html')),
    ]

src/nexttask/views.py
from time import strftime, gmtime
from braces.views import LoginRequiredMixin
import datetime as dt

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.db import transaction
from django.http import HttpResponseServerError, StreamingHttpResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_tables2 import SingleTableView

from .utils import TaskQueryMixin, sync_filter_state
from clog.utils import personalized_now, personalized_timezone
from .models import Task, Tag, NextLine, Estimate, FilterCombo
from .tables import TaskTable, TagTable, TaskDoneSince, TaskAddedToday, EstimateTable, NextLineTable, FilterComboTable  # noqa
from .forms import TagForm, TaskForm, TaskFormNew, TaskFormEdit, NextLineForm  # noqa
from .toggl import start_toggl_timer, get_toggl_duration, map_toggl_tags_internal, map_toggl_tasks_internal, get_toggl_durations_internal  # noqa
from .phabricator import sync_from_phab
from .airtable import sync_phab_to_airtable

from . import estimation
from . import report
from . import toggl


#################################################################################
# Tag LCRUD
#################################################################################


class TagList(LoginRequiredMixin, SingleTableView):
    queryset = Tag.objects.all()
    table_class = TagTable

    def get_queryset(self):
        qs = Tag.objects.same_user(user=self.request.user)
        return qs


class TagCreate(LoginRequiredMixin, CreateView):
    model = Tag
    form_class = TagForm

    def get_success_url(self):
        return reverse('nexttask:tag_list')

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(TagCreate, self).form_valid(form)


class TagRead(LoginRequiredMixin, DetailView):
    model = Tag


class TagUpdate(LoginRequiredMixin, UpdateView):
    model = Tag
    form_class = TagForm

    def get_success_url(self):
        return reverse('nexttask:tag_read', kwargs={
            'pk': self.object.pk,
        })


class TagDelete(LoginRequiredMixin, DeleteView):
    model = Tag
    success_url = reverse_lazy('nexttask:tag_list')


#################################################################################
# FilterCombo LCRUD
#################################################################################

class FilterComboList(LoginRequiredMixin, SingleTableView):
    table_class = FilterComboTable

    def get_context_data(self, **kwargs):
        context = super(FilterComboList, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        qs = FilterCombo.objects.same_user(user=self.request.user)
        return qs


class FilterComboRead(LoginRequiredMixin, DetailView):
    model = FilterCombo

    def get_context_data(self, **kwargs):
        context = super(FilterComboRead, self).get_context_data(**kwargs)
        return context


#################################################################################
# NextLine LCRUD
#################################################################################


class NextLineList(LoginRequiredMixin, SingleTableView):
    table_class = NextLineTable

    def get_context_data(self, **kwargs):
        context = super(NextLineList, self).get_context_data(**kwargs)
        context['show_archived'] = self.request.GET.get('show_archived', '')
        return context

    def get_queryset(self):
        request = self.request
        show_archived = request.GET.get('show_archived', '')

        if show_archived:
            qs = NextLine.objects.same_user_all(user=request.user)
        else:
            qs = NextLine.objects.same_user(user=request.user)

        return qs


class NextLineCreate(LoginRequiredMixin, CreateView):
    model = NextLine
    form_class = NextLineForm

    def get_success_url(self):
        return reverse('nexttask:nextline_list')

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(NextLineCreate, self).form_valid(form)


class NextLineRead(LoginRequiredMixin, DetailView):
    model = NextLine

    def get_context_data(self, **kwargs):
        context = super(NextLineRead, self).get_context_data(**kwargs)
        context['related_tasks'] = kwargs['object'].tasks.all().order_by('date_resolved', 'task_order')  # noqa
        return context


class NextLineUpdate(LoginRequiredMixin, UpdateView):
    model = NextLine
    form_class = NextLineForm

    def get_success_url(self):
        return reverse('nexttask:nextline_read', kwargs={
            'pk': self.object.pk,
        })


class NextLineDelete(LoginRequiredMixin, DeleteView):
    model = NextLine
    success_url = reverse_lazy('nexttask:tag_list')


#################################################################################
# Task LCRUD
#################################################################################


class TaskCreate(LoginRequiredMixin, CreateView, TaskQueryMixin):
    model = Task
    form_class = TaskFormNew

    def get_form_kwargs(self):
        kwargs = super(TaskCreate, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self, **kwargs):
        context = super(TaskCreate, self).get_context_data(**kwargs)
        # If we got a return_url (i.e., if this url was called from
        # somewhere other than the task list, use it.
        # otherwise, assume we came from the task list and return there

        # Even if we got here with a POST, return_url is stored in the GET
        return_url = self.request.GET.get('return_url', None)
        if not return_url:
            return_url = reverse_lazy('nexttask:task_list')

        messages.success(self.request, f'Added task')
        return f"{return_url}?{context['pass_on_params']}"

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        form.instance.date_added = personalized_now(user)
        put_at_top = form.cleaned_data.get('put_at_top')
        if put_at_top == 'top':
            move_up = True
        elif put_at_top == 'bottom':
            move_up = False
        else:
            return HttpResponseServerError("Invalid deletion")
        working_filter = sync_filter_state(self.request)[0]
        with transaction.atomic():
            form.instance.task_order = Task.get_next_order(user=user,
                                                           move_up=move_up,
                                                           **working_filter)
            form.save()

        return super(TaskCreate, self).form_valid(form)


class TaskList(LoginRequiredMixin, SingleTableView, TaskQueryMixin):
    queryset = Task.objects.all()
    table_class = TaskTable
    add_task_form = TaskForm

    def get_context_data(self, **kwargs):
        context = super(TaskList, self).get_context_data(**kwargs)
        request = self.request
        working_filter, pass_on_params = sync_filter_state(request)
        context['working_filter'] = working_filter
        context['pass_on_params'] = pass_on_params
        context['now'] = personalized_now(request.user)
        include_tag_list = working_filter.get('include_tag_list')
        if include_tag_list:
            default_tag = working_filter['include_tag_list'][0]
            context['default_tag_name'] = default_tag.name
            context['default_tag_id'] = default_tag.id
        return context

    def get_queryset(self, **kwargs):
        """
        Always apply user filter.  Other filters will be applied in the filter class
        """
        request = self.request
        user = request.user
        qs = super(TaskList, self).get_queryset()
        qs = qs.same_user(user)
        working_filter = sync_filter_state(request)[0]
        qs = qs.with_filters(user, **working_filter)
        return qs


class TaskRead(LoginRequiredMixin, DetailView, TaskQueryMixin):
    model = Task
    form_class = TaskForm


class TaskUpdate(LoginRequiredMixin, UpdateView, TaskQueryMixin):
    model = Task
    form_class = TaskFormEdit

    def get_success_url(self, **kwargs):
        context = super(TaskUpdate, self).get_context_data(**kwargs)
        return_url = reverse('nexttask:task_read',
                             kwargs={'pk': self.object.pk, })
        return_url += "?" + context['pass_on_params']
        return return_url

    def get_form_kwargs(self):
        kwargs = super(TaskUpdate, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class TaskDelete(LoginRequiredMixin, DeleteView, TaskQueryMixin):
    model = Task

    def delete(self, request, *args, **kwargs):
        self.obj = self.get_object()
        if self.obj.user != request.user:
            return HttpResponseServerError("Invalid deletion")
        self.obj.date_deleted = personalized_now(request.user)
        self.obj.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return_url = reverse_lazy('nexttask:task_list') +\
                     "?" + self.context['pass_on_params']
        return return_url


#################################################################################
# Other views
#################################################################################


class EstimateList(LoginRequiredMixin, SingleTableView):
    queryset = Estimate.objects.all()
    table_class = EstimateTable

    def get_context_data(self, **kwargs):
        context = super(EstimateList, self).get_context_data(**kwargs)

src/nexttask/templates/nexttask/dj2_base_table.html
{% spaceless %}
{% load django_tables2 %}
{% load i18n %}
{% if table.page %}
<div class="table-container">
{% endif %}
{% block table %}
<table{% if table.attrs %} {{ table.attrs.as_html }}{% endif %}>
    {% spaceless %}
    {% block table.thead %}
    <thead>
        <tr>
        {% for column in table.columns %}
            {% if column.orderable %}
            <th {{ column.attrs.th.as_html }}><a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a></th>
            {% else %}
            <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
            {% endif %}
        {% endfor %}
        </tr>
    {% block table.extrathead %}
    {% endblock table.extrathead %}
    </thead>
    {% endblock table.thead %}
    {% block table.tbody %}
    <tbody>
        {% for row in table.page.object_list|default:table.rows %} {# support pagination #}
        {% block table.tbody.row %}
        <tr class="{{ forloop.counter|divisibleby:2|yesno:"even,odd" }}"> {# avoid cycle for Django 1.2-1.6 compatibility #}
            {% for column, cell in row.items %}
                <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
            {% endfor %}
        </tr>
        {% endblock table.tbody.row %}
        {% empty %}
        {% if table.empty_text %}
        {% block table.tbody.empty_text %}
        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
        {% endblock table.tbody.empty_text %}
        {% endif %}
        {% endfor %}
    </tbody>
    {% endblock table.tbody %}
    {% block table.tfoot %}
    <tfoot></tfoot>
    {% endblock table.tfoot %}
    {% endspaceless %}
</table>
{% endblock table %}

{% if table.page %}
{% with table.page.paginator.count as total %}
{% with table.page.object_list|length as count %}
{% block pagination %}
<ul class="pagination">
    {% if table.page.has_previous %}
    {% spaceless %}{% block pagination.previous %}<li class="previous"><a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}">{% trans "Previous" %}</a></li>{% endblock pagination.previous %}{% endspaceless %}
    {% endif %}

    {% if table.page.has_previous or table.page.has_next %}
    {% spaceless %}{% block pagination.current %}<li class="current">{% blocktrans with table.page.number as current and table.paginator.num_pages as total %}Page {{ current }} of {{ total }}{% endblocktrans %}</li>{% endblock pagination.current %}{% endspaceless %}
    {% endif %}

    {% if table.page.has_next %}
    {% spaceless %}{% block pagination.next %}<li class="next"><a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}">{% trans "Next" %}</a></li>{% endblock pagination.next %}{% endspaceless %}
    {% endif %}

    {% spaceless %}{% block pagination.cardinality %}<li class="cardinality">{% if total != count %}{% blocktrans %}{{ count }} of {{ total }}{% endblocktrans %}{% else %}{{ total }}{% endif %} {% if total == 1 %}{{ table.data.verbose_name }}{% else %}{{ table.data.verbose_name_plural }}{% endif %}</li>{% endblock pagination.cardinality %}{% endspaceless %}
</ul>
{% endblock pagination %}
{% endwith %}
{% endwith %}
</div>
{% endif %}
{% endspaceless %}

src/nexttask/templates/nexttask/get_toggl_durations.html
<h2>Totals:</h2>
{% for item in results %}
<p>{{ item.0 }}: {{ item.1|length }}
{% endfor %}

src/nexttask/templates/nexttask/import_results.html
{% extends "base_nexttask.html" %}

{% block content %}

Import complete.

<p>Rows imported: {{ success_count }}
<p>Rows failed: {{ failure_count }}
{% endblock %}

src/nexttask/templates/nexttask/nextline_form.html
{% extends "base_nexttask.html" %}
{% block title %}NextLines: {{ nextline.name}} {% endblock %}

{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item">
  <span class="breadcrumb-end">{{ nextline.name }}</span>
</li>
{% endblock %}


{% block content %}

<form class="pure-form pure-form-aligned" action="?{{pass_on_params}}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="pure-form-button pure-form-button-primary" id="save" type="submit" value="Done">Save</button>
</form>

{% endblock content %}

src/nexttask/templates/nexttask/notice.html
{% extends "base_nexttask.html" %}

{% block content %}

{{ message }}

{% endblock content %}

src/nexttask/templates/nexttask/tag_list.html
{% extends "base_nexttask.html" %}
{% block title %}Tags{% endblock %}
{% load render_table from django_tables2 %}

{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item">
  <span class="breadcrumb-end">All Tags</span>
</li>

{% endblock %}

{% block content %}
<div class="main-content">
{% render_table table %}
</div>
<div class="layout-columns shadowbar">
  <span>
    <a class="pure-button pure-button-primary"
       href="{% url 'nexttask:tag_create' %}"
       id="new-tag">New Tag
    </a>
  </span>
</div>


{% endblock content %}

src/nexttask/templates/nexttask/tag_name_column.html
<a class="tag_name" href="{% url 'nexttask:tag_read' record.pk %}"
   title="View details">{{ record.name }}</a>

src/nexttask/templates/nexttask/task_confirm_delete.html
{% extends "base_nexttask.html" %}

{% block content %}
<div class="main-content">

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete {{ object }}"?>
</form>
</div>

{% endblock content %}

src/nexttask/templates/nexttask/task_date_added_column.html
{% load humanize %}
{% load timetags %}
<span class="deemphasize" title="{{ record.date_added|naturalday }}">{{ record.date_added|naturaldayplus }}</span>

src/nexttask/templates/nexttask/task_done_column.html
<a class="pure-button mark_done" href="{% url 'nexttask:mark_task_done' record.pk %}?{{pass_on_params}}"
   title="Mark {{ record.name }} as done">✓</a>

src/nexttask/templates/nexttask/task_duration_column.html
{% load timetags %}
{{record.duration|singleunittime }}

src/nexttask/templates/nexttask/task_estimate_column.html
{% load humanize %}

{% load timetags %}
<span title="Will take {{record.forecast_duration|singleunittime}}.">{{record.estimate }}</span>

src/nexttask/templates/nexttask/task_list.html
{% extends "base_nexttask.html" %}

{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load tag_filter %}
{% load breadcrumbs %}

{% block title %}Tasks {% if tag_list_pretty %}| {{tag_list_pretty}} {% endif %}{% endblock %}

{% block breadcrumb_trail %}
{{ block.super }}
{% breadcrumb_tasks %}
{% endblock %}

{% block content %}
<div id="layout" class="main-content layout-columns">
  <div>
    <div>
      {% render_table table %}
    </div>
  </div>
  <nav>
    {% task_filterbar %}
  </nav>
</div>
<div class="layout-columns layout-0 shadowbar">
  <a class="pure-button" href="{% url 'nexttask:task_create' %}?{{pass_on_params}}" method="GET" id="new_task">New Task</a>
  <a class="pure-button" href="{% url 'nexttask:phabricator_sync' %}?{{pass_on_params}}&tag={{default_tag_id}}" id="phab_sync">Sync from Phabricator</a>
  <a class="pure-button" href="{% url 'nexttask:update_all_estimates' %}?{{pass_on_params}}&tag={{default_tag_id}}" id="upd_all_est">Update All Estimates</a>
</div>

{% endblock content %}

src/nexttask/templates/nexttask/task_name_column.html
{% load humanize %}
{% load timetags %}

<a href="{% url 'nexttask:task_update' record.pk %}?{{pass_on_params}}"
   class="taskname"
   title="{{ record.name }}">
  
  {% if record.date_resolved %}
  <span title="Closed {{ record.date_resolved }}"><strike>{{ record.name|truncatechars:50 }}</strike></span>
  {% else %}
  {{ record.name|truncatechars:50 }}
  {% endif %}

  {% for link in record.link_list %}
    <br/><a class="{% if link.2 == 'closed' %}closed_remote{% else %}open_remote{% endif %}"
        href="{{ link.0 }}">{{ link.3 }}</a></p>
  {% endfor %}

</a>

{% if record.is_final_for_nextline %}
<p>Final task for Nextline 
  <a href="{% url 'nexttask:nextline_read' record.nextline.pk %}" class="nextline">
    {{record.nextline }}
  </a>
  due 
  {% if record.nextline.is_late %}
  <span class="late" title="{{record.nextline.target_completion}}">{{record.nextline.target_completion|naturaldayplus }} (LATE)</span>
  {% else %}
  <span class="early" title="{{record.nextline.target_completion}}">{{record.nextline.target_completion|naturaldayplus }}</span>
  {% endif %}
  <a href="{% url 'nexttask:nextline_move_to_top' record.nextline.pk %}?{{pass_on_params}}"
     class="pure-button move_nextline_to_top"
     title="Move NextLine to top">
     ↥
     </a>
</p>
{% endif %}

{% if show_snoozed and record.wait_until > now %}
  snoozed until {{ record.wait_until|naturaltime }}
{% endif %}

{% if record.date_resolved %}
  Closed {{ record.date_resolved|naturaltime }}
{% endif %}