src/clog/urls.py
from django.urls import path

from . import views

app_name = 'clog'

urlpatterns = [
    path('', views.index, name='index'),

    path('var/<int:pk>/',
         views.VariableDetail.as_view(),
         name='variable_detail'),

    path('var/<int:pk>/update/',
         views.VariableUpdate.as_view(),
         name='variable_update'),

    path('var/create/',
         views.VariableCreate.as_view(),
         name='variable_create'),

    path('charts/', views.update_charts, name='refresh_charts'),

    path('import_vars/', views.import_vars, name='import_vars'),

    path('import_entries/', views.import_entries, name='import_entries'),

    path('logentry/create/',
         views.logentry_create,
         name='logentry_create'),
    path('logentry/<int:pk>/',
         views.logentry_detail,
         name='logentry_detail'),
    path('logentry/<int:pk>/update/',
         views.logentry_update,
         name='logentry_update'),

    path('sharewith_list', views.ShareList.as_view(), name='share_index'),

    path('share/<int:pk>/',
         views.shareview,
         name='share_view'),

    path('share/<int:pk>/send_daily/',
         views.send_daily,
         name='send_daily'),

    path('share/<int:pk>/send_weekly/',
         views.send_weekly,
         name='send_weekly'),

    path('sharewith/<int:pk>/',
         views.ShareDetail.as_view(),
         name='share_detail'),

    path('sharewith/create/',
         views.ShareCreate.as_view(),
         name='share_create'),

    path('sharewith/<int:pk>/update/',
         views.ShareUpdate.as_view(),
         name='share_update'),

    path('<int:pk>/snooze',
         views.snooze,
         name='snooze'),

]

src/nexttask/urls.py
from django.urls import path
from nexttask import views

app_name = 'nexttask'

urlpatterns = [
    path('',
         views.TaskList.as_view(),
         name='task_list'),

    path('donesince/',
         views.TaskDoneSince.as_view(),
         name='task_done_since'),

    path('addedtoday/',
         views.TaskAddedToday.as_view(),
         name='task_added_today'),

    path('up_all_est/',
         views.update_all_estimates,
         name='update_all_estimates'),

    path('create/',
         views.TaskCreate.as_view(),
         name='task_create'),

    path('<int:pk>/',
         views.TaskRead.as_view(),
         name='task_read'),

    path('<int:pk>/move/',
         views.move_task,
         name='move_task'),

    path('<int:pk>/move_to_edge/',
         views.move_task_to_edge,
         name='move_task_to_edge'),

    path('<int:pk>/toggl_start/',
         views.start_toggl,
         name='start_toggl'),

    path('<int:pk>/snooze/',
         views.snooze,
         name='snooze'),

    path('<int:pk>/update/',
         views.TaskUpdate.as_view(),
         name='task_update'),

    path('<int:pk>/delete/',
         views.TaskDelete.as_view(),
         name='task_delete'),

    path('<int:pk>/explode/',
         views.explode,
         name='explode'),

    path('<int:pk>/slice/<int:key>',
         views.slice,
         name='slice'),

    path('<int:pk>/resolve_row/<int:key>',
         views.resolve_row,
         name='resolve_row'),

    path('<int:pk>/cut_row/<int:key>',
         views.cut_row,
         name='cut_row'),

    path('<int:pk>/done/',
         views.mark_task_done,
         name='mark_task_done'),

    path('tag/',
         views.TagList.as_view(),
         name='tag_list'),

    path('tag/create/',
         views.TagCreate.as_view(),
         name='tag_create'),

    path('tag/<int:pk>/',
         views.TagRead.as_view(),
         name='tag_read'),

    path('tag/<int:pk>/update/',
         views.TagUpdate.as_view(),
         name='tag_update'),

    path('tag/<int:pk>/delete/',
         views.TagDelete.as_view(),
         name='tag_delete'),

    path('mode/',
         views.FilterComboList.as_view(),
         name='filtercombo_list'),

    path('mode/<int:pk>/',
         views.FilterComboRead.as_view(),
         name='filtercombo_read'),

    path('nextline/',
         views.NextLineList.as_view(),
         name='nextline_list'),

    path('nextline/create/',
         views.NextLineCreate.as_view(),
         name='nextline_create'),

    path('nextline/<int:pk>/',
         views.NextLineRead.as_view(),
         name='nextline_read'),

    path('nextline/<int:pk>/update/',
         views.NextLineUpdate.as_view(),
         name='nextline_update'),

    path('nextline/<int:pk>/delete/',
         views.NextLineDelete.as_view(),
         name='nextline_delete'),

    path('nextline/<int:pk>/move_to_top/',
         views.move_nextline_to_top,
         name='nextline_move_to_top'),

    path('estimates/',
         views.EstimateList.as_view(),
         name='estimate'),

    path('phab_sync/',
         views.phabricator_sync,
         name='phabricator_sync'),

    path('airtable/',
         views.airtable_test,
         name='airtable_test'),

    path('map_toggl_tags/',
         views.map_toggl_tags,
         name='map_toggl_tags'),

    path('map_toggl_tasks/',
         views.map_toggl_tasks,
         name='map_toggl_tasks'),

    path('get_toggl_durations/',
         views.get_toggl_durations,
         name='get_toggl_durations'),
]

src/whatnext/urls.py
"""whatnext URL Configuration
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.urls import include, path
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'), # NOQA  https://stackoverflow.com/questions/35804554/importing-django-contrib-auth-urls-does-not-play-well-with-existing-admin-templa
    path('accounts/', include('django.contrib.auth.urls')),
    path('clog/', include('clog.urls')),
    path('nexttask/', include('nexttask.urls')),
]

if settings.DEBUG:
    from django.views import defaults
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += [
        path(r'media/<path>', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        path('500/', defaults.server_error, name='500'),
        path('styleguide', TemplateView.as_view(template_name='styleguide.html')),
    ]

src/nexttask/models.py
import datetime as dt
from decimal import Decimal
from functools import reduce
import operator
import re

from django.db import models, connection, transaction
from django.db.models import Q
from django.utils import timezone
from django.contrib.auth.models import User
from clog.utils import personalized_midnight, personalized_now


class NotesLine():
    """One row in a Task Notes field, parsed from raw text"""
    def __init__(self, indent=0, status=None,
                 subtask=None, remainder=''):
        self.indent = indent
        self.status = status
        self.subtask = subtask
        self.remainder = remainder

    def __repr__(self):
        return '{0}, Indent {1}, status {2}, subtask {3}'.format(
            self.remainder,
            self.indent,
            self.status,
            self.subtask)


class RemoteSystem(models.Model):
    """Each entry is one instance of a remote system that WhatNext can exchange data with
    """

    TOGGL = 0
    PHABRICATOR = 1
    AIRTABLE = 2
    SYSTEM_CHOICES = (
        (TOGGL, 'Toggl'),
        (PHABRICATOR, 'Phabricator'),
        (AIRTABLE, 'Airtable'),
    )
    system = models.IntegerField(choices=SYSTEM_CHOICES, unique=True)
    api_url = models.URLField()

    def __str__(self):
        return self.SYSTEM_CHOICES[self.system][1]

    class Meta:
        verbose_name = 'Remote System'


class TagQuerySet(models.query.QuerySet):
    def same_user(self, user):
        return self.filter(user=user).exclude(deleted=True)

    def all(self):
        # by default, sort by decreasing popularity

        return self.exclude(deleted=True).annotate(
            num_tasks=models.Count('tags')
        ).order_by('-num_tasks')


class Tag(models.Model):
    """Each tag is a tag that one user may apply to zero or more of their
    tasks."""

    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField()

    objects = TagQuerySet.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('user', 'name',)


class TagRemoteMapping(models.Model):
    """Each entry is the identifier for one tag for one remote system
    """
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    remote_system = models.ForeignKey(RemoteSystem, on_delete=models.CASCADE)
    remote_id = models.CharField(max_length=100)
    url = models.URLField(null=True)

    def __str__(self):
        return "User {user}: {tag} on {remote_system}".format(
            user=self.tag.user,
            tag=self.tag,
            remote_system=self.remote_system)

    class Meta:
        unique_together = ('remote_system', 'tag',)


class NextLineQuerySet(models.query.QuerySet):
    def all(self):
        return self

    def same_user(self, user):
        return self.filter(user=user).exclude(archived=True)

    def same_user_all(self, user):
        return self.filter(user=user)


class NextLine(models.Model):
    """
    Each entry is one NextLine

    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(
        null=False,
        blank=False,
        max_length=500)

    target_completion = models.DateTimeField(
        blank=True,
        null=True)

    archived = models.BooleanField(null=True)

    objects = NextLineQuerySet.as_manager()

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ('user', 'name',)

    @property
    def is_late(self):
        now = personalized_now(self.user)
        more_days = self.forecast_completion
        if not more_days:
            more_days = 0
        forecast_completion_date = now + dt.timedelta(days=more_days)
        if self.target_completion:
            if forecast_completion_date > self.target_completion:
                return True
        return False

    @property
    def open_tasks(self):
        open_tasks = self.tasks.filter(date_resolved__isnull=True)
        return open_tasks

    @property
    def resolved_tasks(self):
        resolved_tasks = self.tasks.filter(date_resolved__isnull=False)
        return resolved_tasks

    @property
    def resolved_date(self):
        """ The most recent resolution date of all related tasks.  If there are
        still open tasks, then this is probably meaningless. """
        last_resolved_task = self.tasks.\
            filter(date_resolved__isnull=False).\
            order_by('date_resolved')
        if last_resolved_task:
            return last_resolved_task[0].date_resolved
        else:
            return None

    @property
    def forecast_completion(self):
        # the date when the final task related to this nextline is forecast
        # to be complete
        last_task = self.tasks.all().\
                     order_by('-task_order').\
                     filter(forecast_completion__isnull=False).\
                     first()

        if not last_task:
            return

        return last_task.forecast_completion

    def move_tasks_to_top(self, working_filter):
        user = self.user
        tasks = self.tasks.\
            filter(date_resolved__isnull=True).\
            order_by('-task_order')
        for task in tasks:
            top_order = Task.get_next_order(
                user=user,
                move_up=True,
                include_tag_list=working_filter.get('include_tag_list'),
                exclude_tag_list=working_filter.get('exclude_tag_list'),
                text_filter=working_filter.get('text_filter'),
                show_closed=False,
                show_hidden=False)

            task.task_order = top_order
            task.save()

        result = '{0} tasks in {1} moved to top'.format(
            tasks.count(), self.name)

        return result


class FilterComboQuerySet(models.query.QuerySet):
    def same_user(self, user):
        return self.filter(user=user)


class FilterCombo(models.Model):
    """Each row is one filter combo for one user.
    Velocity is in seconds per day."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    show_closed = models.BooleanField(null=True)
    show_snoozed = models.BooleanField(null=True)
    text_filter = models.CharField(
        max_length=100,
        null=True,
        blank=True)
    velocity = models.FloatField(
        null=True,
        blank=True)

    class meta:
        unique_together = ('user', 'name')

    def __str__(self):
        return self.name

    objects = FilterComboQuerySet.as_manager()

    def get_filterstate(self):
        result = {}
        result['filtercombo'] = self
        result['show_closed'] = self.show_closed
        result['show_snoozed'] = self.show_snoozed
        result['text_filter'] = self.text_filter

        include_fct = FilterComboTag.objects.filter(
            filtercombo__exact=self,
            tag_selection__exact=FilterComboTag.INCLUDE)
        include_tag_list = []
        for fct in include_fct:
            include_tag_list.append(fct.filter)
        result['include_tag_list'] = include_tag_list

        exclude_fct = FilterComboTag.objects.filter(
            filtercombo__exact=self,
            tag_selection__exact=FilterComboTag.EXCLUDE)
        exclude_tag_list = []
        for fct in exclude_fct:
            exclude_tag_list.append(fct.filter)
        result['exclude_tag_list'] = exclude_tag_list

        return result


class TaskQuerySet(models.query.QuerySet):
    def all(self):
        return self.filter(date_deleted__isnull=True)

    def done_since(self, filter_date):
        return self.filter(date_resolved__gt=filter_date)

    def added_today(self, user):
        midnight = personalized_midnight(user)
        return self.filter(date_added__gte=midnight)

    def same_user(self, user):
        return self.filter(user=user)

    def with_filters(self, user, include_tag_list=None, exclude_tag_list=None,
                     show_closed=False, show_snoozed=False, text_filter=None,
                     **kwargs):
        if include_tag_list:
            self = self.filter(tags__in=include_tag_list)
        if exclude_tag_list:
            self = self.exclude(tags__in=exclude_tag_list)
        if not show_closed:
            self = self.filter(date_resolved__isnull=True)
        if not show_snoozed:
            now = personalized_now(user)
            self = self.exclude(wait_until__gt=now)
            # Note that using 'exclude' correctly handles
            # two edge cases: where wait_until is null
            # and where it is in the past
        if text_filter:
            self = self.filter(Q(name__icontains=text_filter) |
                               Q(notes__icontains=text_filter))
        return self


class Task(models.Model):
    """Each entry is one completable task.

    current_order, forecast_completion, and forecast_duration are
    derived fields

    Duration and forecast_* are in seconds

    """

    nextline = models.ForeignKey(
        NextLine,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='tasks',
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    current_order = models.IntegerField(
        null=True,
        blank=True)

    date_added = models.DateTimeField(
        default=timezone.now,
        verbose_name="Added")

    date_deleted = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="Deleted")

    date_resolved = models.DateTimeField(
        blank=True,
        null=True)

    duration = models.IntegerField(
        null=True,
        blank=True,
        verbose_name="Actual Duration")

    estimate = models.CharField(
        blank=True,
        verbose_name="Estimate",
        max_length=50)

    forecast_completion = models.FloatField(
        null=True,
        blank=True,
        verbose_name="Forecast days remaining until completion")

src/nexttask/templates/base_nexttask.html
{% extends "base.html" %}
{% load breadcrumbs %}
{% block title %}
Next Task
{% endblock %}

{% block breadcrumb_trail %}
{{ block.super }}

{% autoescape off %}
{% breadcrumb 'nexttask' %}
{% endautoescape %}

{% endblock %}

{% block content %}

{% endblock %}

src/nexttask/templates/filtercombo_selectbar.html
<li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
  <span class="pure-menu-heading">Active Filter Placeholder</span>
  <ul class="pure-menu-children">
    {% if active_filtercombo %}
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="{{ return_url}}?filtercombo=reset">All</a>
    </li>
    {% else %}
    <li class="pure-menu-item pure-menu-selected">
      <a class="pure-menu-link">All</a>
    </li>
    {% endif %}

    {% for record in filtercombo_list %}
    {% if record == active_filtercombo %}
    <li class="pure-menu-item pure-menu-selected">
      <a class="pure-menu-link>{{ record.name }}"></a>
    </li>
    {% else %}
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="{{ return_url}}?filtercombo={{ record.id }}">{{ record.name }}</a>
    </li>
    {% endif%}
    {% endfor %}
    {% if active_filtercombo == 'custom' %}
    <li class="pure-menu-item">
      <a class="pure-menu-link pure-menu-selected">Custom</a>
    </li>
    {% else %}
    <li class="pure-menu-item">
      <a class="pure-menu-link" href="{{ return_url}}?filtercombo=custom&{{ pass_on_params}}">Custom</a>
    </li>
    {% endif %}
  </ul>
</nav>

src/nexttask/templates/first_task_row.html
<div class="layout-columns">
  <div>
    {% include "includes/task_notes_field_rendered.html" %}
  </div>
  
  <div class="layout-rows layout-flexend">
    {% include "includes/task_bottom_bar.html" %}
  </div>
</div>

src/nexttask/templates/task_filterbar.html
<div class="layout-rows" id="filterbar">
  <form class="pure-form" action="" method="get">
    <button class="pure-button" id="filter">
      Update Filter
    </button>
    <ul>
      <li>
        
        <div id="div_id_show_closed">
          <div>
            <label for="id_show_closed">
              <input 
	        class="checkboxinput" 
	        id="id_show_closed" 
	        name="show_closed" 
	        type="checkbox"
	        {% if show_closed %} checked="checked" {% endif %}
	        />
              Show Closed Tasks
            </label>
          </div>
        </div>
      </li>
      
      <li>
        <div id="div_id_show_snoozed">
          <div>
            <label for="id_show_snoozed">
              <input
	        class="checkboxinput"
	        id="id_show_snoozed"
	        name="show_snoozed"
	        type="checkbox" 
	        {% if show_snoozed %} checked="checked" {% endif %}
	        />
              Show Snoozed Tasks
            </label>
          </div>
        </div>
      </li>

      <li>
        <div id="div_id_name">
          <label for="id_name">
            Text includes ...
          </label>
          <div>
            <input
              id="id_text_filter"
              name="text_filter"
              type="text"
              size="10"
              value="{% if text_filter%}{{ text_filter }}{% endif %}" />
          </div>
          <br/>
        </div>
      </li>

      <li>
        <span class="include_tag">Include</span>
        <span class="exclude_tag">Exclude</span>
      </li>

      {% for record in tag_queryset %}
      <li>
        <input class="include_tag"
	       type="checkbox" 
	       {% if record.id in include_tags %}checked="checked"{% endif%}
	       name="tags" 
	       value="{{record.id}}" />

        <label class="filter_tag_name">{{ record.name }}</label>

        <input class="exclude_tag"
               type="checkbox" 
	       {% if record.id in exclude_tags %}checked="checked"{% endif%}
	       name="exclude_tags" 
	       value="{{record.id}}" />
        
      </li>
      {% endfor %}

    </ul>
    <button class="pure-button" id="filter bottom">
      Update Filter
    </button>
  </form>
</div>

src/nexttask/templates/task_notes.html
<ul class="whatnext_outline">
{% for row in rendered_notes %}
  {% for i in row.indent %}
      <ul>
        <li {% if forloop.last %} class="{{ row.class }}" {% endif %}>
  {% endfor %}
  {% for i in row.outdent %}
        </ul>
      </li>
  {% endfor %}
  {% if not row.indent %}
    <li class="{{ row.class }}">
  {% endif %}

  {% if row.url %}
  <a class="{{ row.class }}" href="{{ row.url }}">{{ row.subtask_name }}</a>
  {% else %}
  <form method="POST" name="slice_{{ row.key }}" action="{{ row.slice_url }}?{{ pass_on_params }}">
    <span class="{{ row.class }}">{{ row.html|safe }}</span>
    <button class="pure-button" type="submit" alt="Slice into subtask">✀</button>
    {% csrf_token %}  </form>
  {% endif %}

  {% if row.resolve_url %}
  <form class="pure-form" method="POST" name="resolve_{{ row.key }}" action="{{ row.resolve_url }}?{{ pass_on_params }}">
    <input type="hidden" name="resolution" value="done"/>
    <button class="pure-button" type="submit" alt="Mark Done">🗹</button>
    {% csrf_token %}  </form>
  {% endif %}

  {% if row.cut_url %}
  <form class="pure-form" method="POST" name="cut_{{ row.key }}" action="{{ row.cut_url }}?{{ pass_on_params }}">
    <input type="hidden" name="resolution" value="done"/>
    <button class="pure-button" type="submit" alt="Mark Done">drop</button>
    {% csrf_token %}  </form>
  {% endif %}

  </li>
{% endfor %}

</ul>