src/clog/urls.py
from django.urls import path

from . import views

app_name = 'clog'

urlpatterns = [
    path('', views.index, name='index'),

    path('var/<int:pk>/',
         views.VariableDetail.as_view(),
         name='variable_detail'),

    path('var/<int:pk>/update/',
         views.VariableUpdate.as_view(),
         name='variable_update'),

    path('var/create/',
         views.VariableCreate.as_view(),
         name='variable_create'),

    path('charts/', views.update_charts, name='refresh_charts'),

    path('import_vars/', views.import_vars, name='import_vars'),

    path('import_entries/', views.import_entries, name='import_entries'),

    path('logentry/create/',
         views.logentry_create,
         name='logentry_create'),
    path('logentry/<int:pk>/',
         views.logentry_detail,
         name='logentry_detail'),
    path('logentry/<int:pk>/update/',
         views.logentry_update,
         name='logentry_update'),

    path('sharewith_list', views.ShareList.as_view(), name='share_index'),

    path('share/<int:pk>/',
         views.shareview,
         name='share_view'),

    path('share/<int:pk>/send_daily/',
         views.send_daily,
         name='send_daily'),

    path('share/<int:pk>/send_weekly/',
         views.send_weekly,
         name='send_weekly'),

    path('sharewith/<int:pk>/',
         views.ShareDetail.as_view(),
         name='share_detail'),

    path('sharewith/create/',
         views.ShareCreate.as_view(),
         name='share_create'),

    path('sharewith/<int:pk>/update/',
         views.ShareUpdate.as_view(),
         name='share_update'),

    path('<int:pk>/snooze',
         views.snooze,
         name='snooze'),

]

src/whatnext/urls.py
"""whatnext URL Configuration
"""

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.urls import include, path
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'), # NOQA  https://stackoverflow.com/questions/35804554/importing-django-contrib-auth-urls-does-not-play-well-with-existing-admin-templa
    path('accounts/', include('django.contrib.auth.urls')),
    path('clog/', include('clog.urls')),
    path('nexttask/', include('nexttask.urls')),
]

if settings.DEBUG:
    from django.views import defaults
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += [
        path(r'media/<path>', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        path('500/', defaults.server_error, name='500'),
        path('styleguide', TemplateView.as_view(template_name='styleguide.html')),
    ]

src/clog/forms.py
from django import forms

from .models import Variable, ShareWith


class LogEntryBoolForm(forms.Form):
    variable = forms.ModelChoiceField(
        queryset=Variable.objects.order_by('order'))
    log_date = forms.DateField()
    value = forms.NullBooleanField()


class VariableForm(forms.ModelForm):
    class Meta:
        model = Variable
        fields = ['name', 'short_name', 'remind', 'type', 'order', 'archived',
                  'target_min', 'target_max', 'good_min', 'good_max',
                  'okay_min', 'okay_max', 'bad_min', 'bad_max']


class ShareForm(forms.ModelForm):
    vars = forms.ModelMultipleChoiceField(
        queryset=Variable.objects.all(),
        widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = ShareWith
        fields = ['share_with_email', 'vars']

    def __init__(self, *args, **kwargs):
        share_user = kwargs.pop('share_user')
        super(ShareForm, self).__init__(*args, **kwargs)
        self.fields['vars'].queryset = Variable.objects.for_user(share_user).order_by('order')


class UploadVarsForm(forms.Form):
    file = forms.FileField()


class UploadEntriesForm(forms.Form):
    file = forms.FileField()

src/clog/views.py
import datetime as dt
import logging
import pandas as pd

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import SuspiciousOperation
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseServerError
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic


from . import models
from . import forms
from . import report
from . import utils


class VariableDetail(generic.DetailView, LoginRequiredMixin):
    model = models.Variable
    context_object_name = 'variables'


class VariableCreate(generic.CreateView, LoginRequiredMixin):
    model = models.Variable
    fields = ['name', 'type', 'remind', 'order',
              'good_min', 'good_max',
              'okay_min', 'okay_max',
              'bad_min', 'bad_max']

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super(VariableCreate, self).form_valid(form)


class VariableUpdate(generic.edit.UpdateView, LoginRequiredMixin):
    model = models.Variable
    template_name = 'clog/variable_form.html'
    form_class = forms.VariableForm


class ShareList(generic.list.ListView, LoginRequiredMixin):
    """List of all shares for this user"""
    model = models.ShareWith
    template_name = 'clog/share_list.html'

    def get_queryset(self):
        return models.ShareWith.objects.filter(share_from=self.request.user)


class ShareCreate(generic.CreateView, LoginRequiredMixin):
    model = models.ShareWith
    template_name = 'clog/share_form.html'
    fields = ['share_with_email']

    def form_valid(self, form):
        sharewith = form.save(commit=False)
        sharewith.share_from = self.request.user
        return super(ShareCreate, self).form_valid(form)


class ShareDetail(generic.DetailView, LoginRequiredMixin):
    model = models.ShareWith
    template_name = 'clog/share_detail.html'
    context_object_name = 'shares'

    def get_context_data(self, *args, **kwargs):
        context = super(ShareDetail, self).get_context_data(*args, **kwargs)
        yesterday = utils.personalized_midnight(self.request.user).date() - dt.timedelta(days=1)
        week_ago = yesterday - dt.timedelta(days=6)
        two_weeks_ago = week_ago - dt.timedelta(days=7)
        sharewith = context['object']
        sharevars = models.Variable.objects.filter(
            sharevariable__share_with=sharewith)
        context['logentry_list'] = sharevars
        context['yesterday'] = yesterday
        context['week_ago'] = week_ago
        context['yesterday_logentries'] = context['object'].daily_logentries(yesterday)
        count_report = context['object'].count_report(week_ago, yesterday)
        prev_count_report = context['object'].count_report(two_weeks_ago, week_ago)
        combined_count_report = zip(count_report, prev_count_report)
        context['count_report'] = combined_count_report
        return context


class ShareUpdate(generic.edit.UpdateView, LoginRequiredMixin):
    model = models.ShareWith
    template_name = 'clog/share_form.html'
    form_class = forms.ShareForm

    def dispatch(self, *args, **kwargs):
        return super(ShareUpdate, self).dispatch(*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(ShareUpdate, self).get_form_kwargs()
        kwargs.update({'share_user': self.request.user})
        return kwargs

    def form_valid(self, form):
        form_sharewith = self.object
        selected_vars = form['vars'].value()
        # delete all ShareVariable belonging to this ShareCreate
        models.ShareVariable.objects.filter(share_with=form_sharewith).delete()
        # add back ShareVariable as indicated
        for var in selected_vars:
            try:
                form_var = models.Variable.objects.get(pk=var)
                models.ShareVariable.objects.create(
                    share_with=form_sharewith,
                    share_var=form_var
                )
            except Exception:
                raise SuspiciousOperation

        return super(ShareUpdate, self).form_valid(form)


@login_required()
def index(request):
    """Home page dashboard"""
    email = request.user.email
    share_list = models.ShareWith.objects.filter(share_with_email=email)
    today = utils.personalized_midnight(request.user).date()
    last_week = today - dt.timedelta(days=7)
    raw_date_range = pd.date_range(start=last_week, end=today)
    date_range = [date.date() for date in raw_date_range]

    var_results = models.Variable.objects.for_user(request.user).order_by('order')

    varreport = models.VariableReport.objects.filter(
        variable__in=var_results,
        log_date__gte=last_week)

    context = {'date_range': date_range,
               'var_results': var_results,
               'varreport': varreport,
               'share_list': share_list}
    return render(request, 'clog/index.html', context)


@login_required()
def shareview(request, pk):
    """render someone else's data shared with user"""
    today = utils.personalized_midnight(request.user).date()
    last_week = today - dt.timedelta(days=7)
    raw_date_range = pd.date_range(start=last_week, end=today)
    date_range = [date.date() for date in raw_date_range]

    sharewith = models.ShareWith.objects.get(pk=pk)

    sharevars = models.Variable.objects.filter(
        sharevariable__share_with=sharewith)

    variable_status = models.VariableStatus.objects.values(
        'weeks_ago', 'variable__name', 'dashboard_status'
    ).filter(
        variable__in=sharevars
    )

    log_results = models.LogEntry.objects.values(
        'pk', 'log_date', 'variable__name', 'bo_value', 'te_value', 'nu_value'
    ).filter(
        variable__in=sharevars
    ).filter(
        log_date__gte=last_week
    ).order_by('log_date')

    log_list = [log for log in log_results]
    varstat_list = [varstat for varstat in variable_status]

    context = {'date_range': date_range,
               'var_results': sharevars,
               'log_list': log_list,
               'varstats': varstat_list,
               'sharewith': sharewith}
    return render(request, 'clog/shareview.html', context)


@login_required
def import_vars(self):
    """Import JSON of variables
    TODO: go through a form to get file
    TODO: apply file size limit in nginx"""
    user = self.user
    models.Variable.load_file('/var/tmp/export_vars.json', user)
    return HttpResponseRedirect(reverse_lazy('clog:index'))


@login_required
def import_entries(self):
    """Import JSON of entries
    TODO: go through a form to get file
    TODO: apply file size limit in nginx"""
    user = self.user
    models.LogEntry.load_file('/var/tmp/export_entries.json', user)
    return HttpResponseRedirect(reverse_lazy('clog:index'))


@login_required
def update_charts(self):
    """Refresh all charts"""
    user = self.user
    var_list = models.Variable.objects.for_user(user)
    for var in var_list:
        report.make_chart(var)
    return HttpResponseRedirect(reverse_lazy('clog:index'))


@login_required()
def logentry_detail(request, pk):
    logentry = get_object_or_404(models.LogEntry, pk=pk)
    return render(request, 'clog/logentry_detail.html', {'logentry': logentry})


@login_required()
def send_daily(request, pk):
    user = request.user
    share_with = models.ShareWith.objects.get(pk=pk)
    result = utils.send_daily_internal(user, share_with)
    return render(request, 'clog/send_email.html', {'body': result})


@login_required()
def send_weekly(request, pk):
    user = request.user
    share_with = models.ShareWith.objects.get(pk=pk)
    result = utils.send_weekly_internal(user, share_with)
    return render(request, 'clog/send_email.html', {'body': result})


@login_required()
def logentry_update(request, pk):
    logentry = get_object_or_404(models.LogEntry, pk=pk)
    new_checked = request.POST.get('checked', None)
    new_value = request.POST.get('value', None)
    if new_checked:
        value = True
    elif new_value:
        value = new_value
    else:
        value = None
    logentry.update_with_value(value)
    return HttpResponseRedirect(reverse_lazy('clog:index'))


@login_required()
def logentry_create(request):
    new_value = request.POST.get('value', None)
    if new_value:
        if new_value == 'on':
            new_value = True
    return_url = request.POST.get('return_url', None)
    date = request.POST.get('date', None)
    variable_id = request.POST.get('variable', None)
    if new_value and date and variable_id:
        models.LogEntry.objects.create_with_value(
            log_date=date,
            variable_id=variable_id,
            value=new_value)
    if not return_url:
        return_url = reverse('clog:index')
    return redirect(return_url)


@login_required
def snooze(request, pk):
    object_clog = models.Variable.objects.get(id=pk)
    if not object_clog:
        return HttpResponseServerError(
            'Clog Variable not found')

    user = request.user

    if object_clog.user != user:
        return HttpResponseServerError(
            'Clog Variable not found')
    return_url = request.GET.get('return_url', '')
    amount = request.GET.get('amount', '')
    now = utils.personalized_now(user)
    if amount == 'later':
        wait_until = now + dt.timedelta(hours=4)
    elif amount == 'tomorrow':
        tomorrow = now.date() + dt.timedelta(days=1)
        tzone = utils.personalized_timezone(user)
        wait_until = dt.datetime(
            year=tomorrow.year,
            month=tomorrow.month,
            day=tomorrow.day,
            hour=0,
            minute=0,
            second=1,
            tzinfo=tzone)
    else:
        return HttpResponseServerError(
            'Amount of snoozing not recognized')

    object_clog.wait_until = wait_until
    object_clog.save()

src/clog/templates/clog/count_report.html
{% if count_report %}
<table class="clog_count_report">
<tr>
<th/>
<th>This Week</th>
<th>Target</th>
<th>Last Week</th>
</tr>
{% for row in count_report %}
{% with var=row.0 prev_var=row.1 %}
<tr>
  <td>{{ var.name }}</td>
  <td>{% include 'includes/report_cell.html' with var=var %}</td>

  <td>{% if var.type == 'me' %}
        {% if var.good_min = var.good_max %}
          {{ var.good_max|floatformat:1 }}
        {% else %}
          {{ var.good_min|floatformat:1 }}–{{ var.good_max|floatformat:1 }}
        {% endif %}
      {% else %}
        {% if var.good_min = var.good_max %}
          {{ var.good_max|floatformat:0 }} day{{var.good_max|pluralize}}
        {% else %}
          {{ var.good_min|floatformat:"0" }}–{{ var.good_max|floatformat:"0" }} days
        {% endif %}
      {% endif %}
   </td>
  <td>{% include 'includes/report_cell.html' with var=prev_var %}</td>
</tr>
{% endwith %}
{% endfor %}
</table>
{% endif %}

src/clog/templates/clog/count_report_email.html
<p>{{ subject }}</p>
{% if count_report %}

{% for row in count_report %}
{% with var=row.0 prev_var=row.1 %}
<strong>{{ var.name }}</strong>
<ul>
  <li>{% include 'includes/report_cell.html' with var=var %}</li>
  <li>Target: 
      {% if var.type == 'me' %}
        {% if var.good_min = var.good_max %}
          {{ var.good_max|floatformat:1 }}
        {% else %}
          {{ var.good_min|floatformat:1 }}–{{ var.good_max|floatformat:1 }}
        {% endif %}
      {% else %}
        {% if var.good_min = var.good_max %}
          {{ var.good_max|floatformat:0 }} day{{var.good_max|pluralize}}
        {% else %}
          {{ var.good_min|floatformat:"0" }}–{{ var.good_max|floatformat:"0" }} days
        {% endif %}
    {% endif %}</li>
  <li>Last Week: {% include 'includes/report_cell.html' with var=prev_var %}</li>
</ul>
{% endwith %}
{% endfor %}
{% else %}
  No information was reported this week.
{% endif %}

src/clog/templates/clog/index.html
{% extends "base.html" %}
{% load static %}
{% load clog_extras %}

{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item"><span class="breadcrumb-end">Life Log</span></li>
{% endblock %}

{% block content %}
<div class="main-content">
<table class="clog_logentry">
  {% include 'includes/dateheader_row.html' with date_range=date_range %}
  {% for variable in var_results %}
  <tr class="clog_variable_row">
    {% include 'includes/variable_header.html' with pk=variable.pk type=variable.type name=variable.name short_name=variable.short_name %} 
    {% include 'includes/variable_chart.html' with variable=variable %}
    {% for date in date_range %}
      {% get_logentry_form_fields varreport variable.id date variable.type as fields %}
      {% include 'includes/variable_cell.html' with variable=variable fields=fields %}
    {% endfor %}
    {% include 'includes/variable_header.html' with pk=variable.pk type=variable.type name=variable.name short_name=variable.short_name %} 
  </tr>
  {% endfor %}
  {% include 'includes/dateheader_row.html' with date_range=date_range %}
</table>
{% if share_list %}
<ul>
  {% for share in share_list %}
    <li><a href="{% url 'clog:share_view' share.pk %}">View shared information from {{ share.share_from }}</a></li>
  {% endfor %}
</ul>
{% endif %}
</div>

<div class="layout-columns shadowbar">
  <span>
    <a class="pure-button"
       id="edit" 
       href="{% url 'clog:variable_create' %}">
       Add Variable
    </a>
  <span>
  </span>
    <a class="pure-button"
       id="edit" 
       href="{% url 'clog:refresh_charts' %}">
       Refresh Charts
    </a>
  <span>
  </span>
    <a class="pure-button"
       id="edit" 
       href="{% url 'clog:share_index' %}">
       Share
    </a>
  <span>
  </span>
    <a class="pure-button"
       id="edit" 
       href="{% url 'clog:import_vars' %}">
       Import Variables
    </a>
  <span>
  </span>
    <a class="pure-button"
       id="edit" 
       href="{% url 'clog:import_entries' %}">
       Import Entries
    </a>
  </span>
</div>

{% endblock %}

src/clog/templates/clog/logentry_detail.html
{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item">
  <span class="breadcrumb-end">{{ logentry.pk }}</span>
</li>

{% endblock %}


{% block content %}
<h1>{{ logentry.pk }}</h1>
<form action="{% url 'clog:logentry_update' logentry.pk %}" method="post">
{% csrf_token %}
<p><input type="text" name="variable" value="{{ logentry.variable }}" /></p>
<p><input type="text" name="log_date" value="{{ logentry.log_date }}" /></p>
<p><input type="text" name="bo_value" value="{{ logentry.bo_value }}" /></p>
<p><input type="text" name="nu_value" value="{{ logentry.nu_value }}" /></p>
<p><input type="text" name="te_value" value="{{ logentry.te_value }}" /></p>
<p><input type="submit" value="Save"/>
</form>
{% endblock %}

src/clog/templates/clog/send_email.html
{% extends "base.html" %}
{% block content %}

{{ body }}
{% endblock %}

src/clog/templates/clog/share_detail.html
{% extends "base.html" %}

{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item">
  <span class="breadcrumb-end">{{ object }}</span>
</li>

{% endblock %}

{% block content %}
<h1>{{ object }}</h1>

<p>Email: {{ object.share_with_email }}</p>


{% if logentry_list %}
  Currently sharing:
  <ul>
    {% for item in logentry_list %}
    <li>{{ item }}</li>
    {% endfor %}
  </ul>

  {% if yesterday_logentries %}
    <p>Daily report for yesterday, {{ yesterday }}, is:</p>
    {% include 'includes/daily_report.html' with logentries=yesterday_logentries %}
    <p><a href="{% url 'clog:send_daily' object.pk %}">Send Daily Email</a>.</p>
  {% else %}
      No data from yesterday
  {% endif %}

  <p>Weekly report for {{ week_ago|date:"l, j M Y" }} to {{ yesterday|date:"l, j M" }} is</p>
  {% include 'includes/count_report.html' with count_report=count_report %}
  <p><a href="{% url 'clog:send_weekly' object.pk %}">Send Weekly Email</a>.</p>

  {% else %}
    Not sharing any variables
  {% endif %}


<p><a id="edit" href="{% url 'clog:share_update' object.pk %}">Edit {{ object }}</a></p>
<p>Stop sharing with {{ object.share_with_email }}</p>

{% endblock %}

src/clog/templates/clog/share_form.html
{% extends "base.html" %}

{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item">
  <span class="breadcrumb-end">Share</span>
</li>

{% endblock %}

{% block content %}
<form action="" method="post" class="share_vars">
    {% csrf_token %}
    {{ form.as_p }}
    <input id="save" type="submit" value="Done">
</form>
{% endblock %}

src/clog/templates/clog/share_list.html
{% extends "base.html" %}
{% load static %}
{% load clog_extras %}


{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item">
  <span class="breadcrumb-end">Sharing</span>
</li>

{% endblock %}

{% block content %}
<h1>Sharing</h1>
<ul>
{% for share in object_list %}
  <li><a href="{% url 'clog:share_detail' share.pk %}">{{ share }}</a>
  </li>
{% empty %}
  <li>Data is not currently shared with anyone else.</li>
{% endfor %}
</ul>

<nav>
  <ul>
    <li><a href="{% url 'clog:share_create' %}">Share data with another person</a></li>
  </ul>
</nav>

{% endblock %}

src/clog/templates/clog/shareview.html
{% extends "base.html" %}
{% load static %}
{% load clog_extras %}
{% block content %}
<p><a href="/clog">Back</a></p>
<h1>Shared Data</h1>
{{ sharewith.share_from }}</h1>
<table class="clog_logentry">
  <tr>
    <th colspan="2"/>
    {% for date in date_range %}
    <th class="clog_datecol{{ forloop.counter }}">
      {% if forloop.counter = 1 or forloop.counter = 8 %}
        {{ date|date:'j M' }}
      {% else %}
        {{ date|date:'j' }}
      {% endif %}
      <br/>{{ date|date:'D' }}
    </th>
    {% endfor %}
    <th/>
  </tr>
  {% for variable in var_results %}
  <tr class="clog_variable_row">
    <th class="clog_varname">
      {% include 'includes/variable_header.html' with pk=variable.pk name=variable.name short_name=variable.name %} 
    </th>
    <td><a href='{{ variable|get_chart_url }}'><img src='{{ variable|get_chart_url }}' style='width: 80px;'/></a></td>
    {% for date in date_range %}
      {% if forloop.counter = 1 %}
        {% varstats_lookup varstats variable.name 1 as class %}
      {% else %}
        {% varstats_lookup varstats variable.name 0 as class %}
      {% endif %}
      <td class="clog_logcell {{ class }} ">
      {% get_logentry_form_fields log_list variable.name date variable.type as fields %}
      {% if not fields.error %}
      <form action="{{ fields.action }}" method="post">
        {% csrf_token %}
        <input name="value" 
               type="{{ fields.type }}"
               class="clog_{{ variable.type }}"
               id="{{ date|date:'c' }}-{{ variable.name }}"
               readonly
               onclick="return false"
               {% if fields.size %}size="{{fields.size }}"{% endif %}
               {% if fields.value %}value="{{ fields.value }}"{% endif %} 
               {% if fields.checked %}checked{% endif %}/>
        {%if fields.type == "checkbox" %}
           <label for="{{ date|date:'c' }}-{{ variable.name }}"/>
        {% endif %}
      </form>
      {% else %}
      Error!
      {% endif %}
    </td>
    {% endfor %}
    <th class="clog_varname">
      {% include 'includes/variable_header.html' with pk=variable.pk name=variable.name short_name=variable.short_name %} 
    </th>
  </tr>
  {% endfor %}
  <tr>
    <th colspan="2"/>
    {% for date in date_range %}
    <th class="clog_datecol{{ forloop.counter }}">
      {% if forloop.counter = 1 or forloop.counter = 8 %}
        {{ date|date:'j M' }}
      {% else %}
        {{ date|date:'j' }}
      {% endif %}
      <br/>{{ date|date:'D' }}
    </th>
    {% endfor %}
    <th/>
  </tr>
</table>

{% endblock %}

src/clog/templates/clog/variable_detail.html
{% extends "base.html" %}

{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item">
  <span class="breadcrumb-end">{{ object.name }}</span>
</li>

{% endblock %}

{% block content %}
<div class="main-content">
<h1>{{ object.name }}</h1>

<p>Name: {{ object.name }}</p>
<p>Short Name: {{ object.short_name }}</p>
<p>Include in What Next: {{ object.remind }}</p>
<p>Type: {{ object.type }}</p>
<p>Order: {{ object.order }}</p>
<p>Target_min: {{ object.target_min }} (only used for Measurement)</p>
<p>Target_min: {{ object.target_min }} (only used for Measurement)</p>
<p>Good_min: {{ object.good_min }} (for Measurement, used for delta)</p>
<p>Good_max: {{ object.good_max }} (for Measurement, used for delta)</p>
<p>Okay_min: {{ object.okay_min }} (not used for Measurement)</p>
<p>Okay_max: {{ object.okay_max }} (not used for Measurement)</p>
<p>Bad_min: {{ object.bad_min }} (not used for Measurement)</p>
<p>Bad_max: {{ object.bad_max }} (not used for Measurement)</p>
</div>

<div class="layout-columns shadowbar">
  <span>
    <a class="pure-button pure-button-primary"
       href="{% url 'clog:variable_update' object.pk %}">
      Edit {{ object.name }}
    </a>
  </span>

  <span>
    <a class="pure-button pure-button-primary pure-button-disabled"
       href="">
      Delete {{ object.name }} (not implemented)
    </a>
  </span>

  <span>
    <a class="pure-button pure-button-primary pure-button-disabled"
       href="">
      Full history (not implemented)
    </a>
  </span>

  <span>
    <a class="pure-button pure-button-primary pure-button-disabled"
       href="">
      Show Chart (not implemented)
    </a>
  </span>

</div>

{% endblock %}

src/clog/templates/clog/variable_form.html
{% extends "base.html" %}


{% block breadcrumb_trail %}
{{ block.super }}
<li class="pure-menu-item">»</li>
<li class="pure-menu-item">
  <span class="breadcrumb-end">{% if object.name %}Edit {{ object.name }} {% else %}New Variable{% endif %}</span>
</li>

{% endblock %}

{% block content %}
<div class="main-content">
<form class="pure-form pure-form-aligned" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="pure-button pure-button-primary" id="save" type="submit" value="Done">Done</button>
</form>
</div>
{% endblock %}

src/clog/templates/clog/variable_whatnext.html
<div class="single_item">
  <div class="name clog_{{ fields.dashboard_status }}">
    {{ variable.name }}
  </div>
  <div class="buttonrow actionrow">
    <div>
      <form action="{{ fields.action }}" method="post">
        {% csrf_token %}
        {% if fields.type == "checkbox" %}
        <input type="hidden"
               name="value"
               class="clog_input clog_{{ variable.type }}"
               id="{{ date|date:'c' }}-{{ variable.name }}"
               value='checked'
               />
        <input type="submit" value="Done"/>
        {% else %}
        <input name="value"
               type="{{ fields.type }}"
               class="clog_input clog_{{ variable.type }}"
               id="{{ date|date:'c' }}-{{ variable.name }}"
               onChange="this.form.submit()"
               {% if fields.size %}size="{{fields.size }}"{% endif %}/>
        {% endif %}
        {% if return_url %}
        <input type="hidden" name="return_url" value="{{ return_url }}"/>
        {% endif %}
        {% if fields.variable %}
        <input type="hidden" name="variable" value="{{ fields.variable }}"/>
        {% endif %}
        {% if fields.date %}
        <input type="hidden" name="date" value="{{ fields.date|date:"c" }}"/>
        {% endif %}
      </form>
    </div>
    <div>
      <a href="{% url 'clog:snooze' variable.pk%}?return_url={{return_url}}&amount=tomorrow">Tomorrow</a>
    </div>
  </div>
</div>